// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// import { Lora, Montserrat, Kapakana } from "next/font/google"

// const lora = Lora({ subsets: ["latin"] })
// const montserrat = Montserrat({ subsets: ["latin"] })
// const kapakana = Kapakana({ subsets: ["latin"] })


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         style={{
//           "--font-body": lora.style.fontFamily,
//           "--font-nav": montserrat.style.fontFamily,
//           "--font-heading": kapakana.style.fontFamily,
//         } as React.CSSProperties}
//       >
//         {children}
//       </body>
//     </html>
//   )
// }

"use client";
import { Lora, Montserrat } from "next/font/google"
import { useEffect } from "react";


const lora = Lora({ subsets: ["latin"] })
const montserrat = Montserrat({ subsets: ["latin"] })

function useBottomOverscrollColor() {
  useEffect(() => {
    const updateOverscrollColor = () => {
      const scrollBottom = window.scrollY + window.innerHeight;
      const pageHeight = document.documentElement.scrollHeight;
      const nearBottom = pageHeight - scrollBottom < 50;
      document.body.style.backgroundColor = nearBottom ? "var(--color-accent-tag)" : "var(--color-background)";
    };

    window.addEventListener("scroll", updateOverscrollColor);
    window.addEventListener("resize", updateOverscrollColor);
    updateOverscrollColor();

    return () => {
      window.removeEventListener("scroll", updateOverscrollColor);
      window.removeEventListener("resize", updateOverscrollColor);
    };
  }, []);
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
  useBottomOverscrollColor();

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Kapakana&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        style={{
          "--font-body": lora.style.fontFamily,
          "--font-nav": montserrat.style.fontFamily,
          "--font-heading": "'Kapakana', serif",
        } as React.CSSProperties}
      >
        {children}
      </body>
    </html>
  )
}